// encoding: utf-8

export const abbreviations = {
  reply: {
    "en-US": ["RE", "Re", "RE", "RE"],
    "en-GB": ["RE", "Re", "RE", "RE"],
    "en-AU": ["RE", "Re", "RE", "RE"],
    "fr": ["RE", "REF", "RE", "RE"],
    "de": ["AW", "Aw", "AW", "AW"],
    "es": ["RE", "RE", "RE", "RE"],
    "ca": ["RE", "RE", "RE", "RE"],
    "it": ["R", "RIF", "R", "R"],
    "ja": ["返", "RE", "Re", "返"],
    "pl": ["Odp", "Odp", "Odp", "Odp"],
    "ar": ["رد", "رد", "رد", "رد"],
    "pt": ["RES", "RE", "RES", "RES"],
    "pt-BR": ["RES", "RE", "RES", "RES"],
    "ko": ["답장", "회신", "RE", "Re"],
    "nl": ["Antw", "Antw.", "Re", "Betr"],
    "nb": ["SV", "SV", "SV", "SV"],
    "ru": ["Ответ", "RE", "Re", "Ответ"],
    "sv": ["SV", "SV", "SV", "SV"],
    "fi": ["VS", "VS", "VS", "VS"],
    "zh-CN": ["回复", "回复", "回复", "回复"],
    "hu": ["Vá", "Vá", "Vá", "Vá"],
    "vi": ["TL", "RE", "Re", "TL"],
    "zh-TW": ["回覆", "回覆", "回覆", "回覆"]
  },
  forward: {
    "en-US": ["FW", "Fwd", "FWD", "Fw"],
    "en-GB": ["FW", "Fwd", "FWD", "Fw"],
    "en-AU": ["FW", "Fwd", "FWD", "Fw"],
    "fr": ["TR", "TR", "TR", "TR"],
    "de": ["WG", "Wg", "WG", "WG"],
    "es": ["RV", "Rv", "Fwd", "FWD"],
    "ca": ["RV", "Rv", "Fwd", "FWD"],
    "it": ["I", "I", "I", "I"],
    "ja": ["転送", "FW", "Fw", "再送"],
    "pl": ["PD", "PD", "PD", "PD"],
    "ar": ["إعادة توجيه", "إعادة توجيه", "إعادة توجيه", "إعادة توجيه"],
    "pt": ["ENC", "Enc", "FW", "Fwd"],
    "pt-BR": ["ENC", "Enc", "FW", "Fwd"],
    "ko": ["FW", "Fw", "FW", "FW"],
    "nl": ["Doorst", "Fwd", "Fw", "Doorst"],
    "nb": ["VS", "VS", "VS", "VS"],
    "ru": ["FW", "Fwd", "FWD", "Fw"],
    "sv": ["VB", "VB", "VB", "VB"],
    "fi": ["VL", "VL", "VL", "VL"],
    "zh-CN": ["转发", "转发", "转发", "转发"],
    "hu": ["Továbbítás", "Továbbítás", "Továbbítás", "Továbbítás"],
    "vi": ["Chuyển tiếp", "FW", "Fwd", "FWD"],
    "zh-TW": ["轉寄", "轉寄", "轉寄", "轉寄"]
  }
};
